# Generated by Django 4.1.3 on 2023-01-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('orb_num', models.CharField(default='', max_length=8)),
                ('data_in_api', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], default='?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('abbreviation', models.CharField(max_length=5)),
                ('current_class', models.CharField(max_length=4)),
                ('deadline_application', models.DateField()),
                ('internship_start', models.DateField()),
                ('internship_end', models.DateField()),
                ('deadline_report1', models.DateField()),
                ('deadline_report2', models.DateField()),
                ('deadline_report3', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VacantPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('currently_open', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.company')),
                ('degree_program', models.ManyToManyField(to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation_no', models.CharField(max_length=1024)),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(default='', max_length=10)),
                ('email', models.CharField(max_length=1024)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=1024)),
                ('degree_program', models.ManyToManyField(to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('application_status', models.CharField(choices=[('a', 'applied'), ('t', 'talks ongoing'), ('y', 'accepted'), ('r', 'rejected'), ('d', 'deleted'), ('o', 'other')], max_length=1)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.student')),
            ],
        ),
    ]
