# Generated by Django 4.1.3 on 2023-01-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255, null=True)),
                ('zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('iso_country_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('orb_num', models.CharField(default='', max_length=8)),
                ('data_in_api', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], default='?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('abbreviation', models.CharField(max_length=5)),
                ('current_class', models.CharField(max_length=4)),
                ('deadline_application', models.DateField()),
                ('internship_start', models.DateField()),
                ('internship_end', models.DateField()),
                ('deadline_report1', models.DateField()),
                ('deadline_report2', models.DateField()),
                ('deadline_report3', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('likes', models.IntegerField(null=True)),
                ('followers', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacantPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('currently_open', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], default='?', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.company')),
                ('degree_program', models.ManyToManyField(to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation_no', models.CharField(max_length=1024)),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(default='', max_length=10)),
                ('email', models.CharField(max_length=1024)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=1024)),
                ('degree_program', models.ManyToManyField(to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('application_status', models.CharField(choices=[('a', 'applied'), ('t', 'talks ongoing'), ('y', 'accepted'), ('r', 'rejected'), ('d', 'deleted'), ('o', 'other')], max_length=1)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('orb_num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=512, null=True)),
                ('name', models.CharField(max_length=512)),
                ('website', models.URLField(null=True)),
                ('industry', models.CharField(max_length=512, null=True)),
                ('employees', models.IntegerField(null=True)),
                ('revenue', models.IntegerField(null=True)),
                ('year_founded', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('favicon', models.URLField(null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamapi.addressdetail')),
                ('facebook_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_account', to='jamapi.socialaccount')),
                ('linkedin_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_account', to='jamapi.socialaccount')),
                ('twitter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_account', to='jamapi.socialaccount')),
            ],
        ),
    ]
