# Generated by Django 4.1.3 on 2023-01-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255, null=True)),
                ('zip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('iso_country_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('orb_num', models.CharField(default='', max_length=8)),
                ('data_in_api', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], default='?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20)),
                ('company_status', models.CharField(max_length=20)),
                ('orb_num', models.BigIntegerField()),
                ('parent_orb_num', models.BigIntegerField(null=True)),
                ('parent_name', models.CharField(max_length=255, null=True)),
                ('branches_count', models.IntegerField()),
                ('subsidiaries_count', models.IntegerField()),
                ('acquired_parent_orb_num', models.BigIntegerField(null=True)),
                ('acquired_parent_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(null=True)),
                ('webdomain', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('naics_code', models.CharField(max_length=20, null=True)),
                ('sic_code', models.CharField(max_length=20, null=True)),
                ('employees_range', models.CharField(max_length=20)),
                ('employees', models.IntegerField(null=True)),
                ('revenue_range', models.CharField(max_length=20)),
                ('revenue', models.IntegerField(null=True)),
                ('year_founded', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('favicon', models.URLField(null=True)),
                ('total_funding', models.IntegerField(null=True)),
                ('last_funding_round_amount', models.IntegerField(null=True)),
                ('last_funding_round_year', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('importance_score', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=20, null=True)),
                ('cusip', models.CharField(max_length=20, null=True)),
                ('market_cap', models.IntegerField(null=True)),
                ('fiscal_year_end', models.CharField(max_length=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lei', models.CharField(max_length=20, null=True)),
                ('cidrs_count', models.IntegerField()),
                ('liveramp_idl_count', models.IntegerField()),
                ('liveramp_device_count', models.IntegerField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamapi.addressdetail')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='jamapi.companydetail')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('abbreviation', models.CharField(max_length=5)),
                ('current_class', models.CharField(max_length=4)),
                ('deadline_application', models.DateField()),
                ('internship_start', models.DateField()),
                ('internship_end', models.DateField()),
                ('deadline_report1', models.DateField()),
                ('deadline_report2', models.DateField()),
                ('deadline_report3', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('likes', models.IntegerField(null=True)),
                ('followers', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacantPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('currently_open', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], default='?', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.company')),
                ('degree_program', models.ManyToManyField(to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamapi.companydetail')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation_no', models.CharField(max_length=1024)),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(default='', max_length=10)),
                ('email', models.CharField(max_length=1024)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1024)),
                ('lastname', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=1024)),
                ('degree_program', models.ManyToManyField(to='jamapi.degreeprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('application_status', models.CharField(choices=[('a', 'applied'), ('t', 'talks ongoing'), ('y', 'accepted'), ('r', 'rejected'), ('d', 'deleted'), ('o', 'other')], max_length=1)),
                ('approval_status', models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamapi.student')),
            ],
        ),
        migrations.AddField(
            model_name='companydetail',
            name='facebook_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_account', to='jamapi.socialaccount'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='googleplus_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='googleplus_account', to='jamapi.socialaccount'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='linkedin_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_account', to='jamapi.socialaccount'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='names',
            field=models.ManyToManyField(blank=True, null=True, to='jamapi.companydetail'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='orb_nums',
            field=models.ManyToManyField(blank=True, null=True, to='jamapi.companydetail'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='twitter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_account', to='jamapi.socialaccount'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='youtube_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_account', to='jamapi.socialaccount'),
        ),
    ]
