# Generated by Django 4.1.3 on 2023-01-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantposition',
            name='approval_status',
            field=models.CharField(choices=[('y', 'yes'), ('?', 'tbd'), ('n', 'no')], default='?', max_length=1),
        ),
    ]
