# Generated by Django 4.1.3 on 2023-01-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='names',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='orb_nums',
        ),
        migrations.RemoveField(
            model_name='technologies',
            name='company',
        ),
    ]
