# Generated by Django 4.1.3 on 2023-01-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0002_remove_companydetail_categories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technologies',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='acquired_parent_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='cik',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='cusip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='employees_range',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='entity_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='fax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='fiscal_year_end',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='importance_score',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='industry',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='lei',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='naics_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='orb_num',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='parent_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='revenue_range',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='sic_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='webdomain',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
