# Generated by Django 4.1.3 on 2023-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0002_file_remove_student_degree_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='orb_num',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
