# Generated by Django 4.1.3 on 2023-01-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0003_delete_technologies_remove_companydetail_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='acquired_parent_name',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='acquired_parent_orb_num',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='branches_count',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='cidrs_count',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='cik',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='company_status',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='cusip',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='employees_range',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='fiscal_year_end',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='googleplus_account',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='importance_score',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='last_funding_round_amount',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='last_funding_round_year',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='lei',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='liveramp_device_count',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='liveramp_idl_count',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='naics_code',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='parent_orb_num',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='revenue_range',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='sic_code',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='subsidiaries_count',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='total_funding',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='webdomain',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='youtube_account',
        ),
    ]
