# Generated by Django 4.1.3 on 2023-01-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0003_remove_companydetail_orb_num_companydetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamapi.companydetail'),
        ),
    ]
