# Generated by Django 4.1.3 on 2023-01-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0004_remove_companydetail_acquired_parent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='linkedin_account',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='twitter_account',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='degree_program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree_program',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='company',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='student',
        ),
        migrations.RemoveField(
            model_name='vacantposition',
            name='company',
        ),
        migrations.DeleteModel(
            name='AddressDetail',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
