# Generated by Django 4.1.3 on 2023-01-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0005_remove_companydetail_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('orb_num', models.CharField(max_length=20, null=True)),
                ('approved_status', models.BooleanField(null=True)),
                ('local_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jamapi.companylocaldetails')),
            ],
        ),
    ]
