# Generated by Django 4.1.3 on 2023-01-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0006_alter_company_custom_companies_alter_company_orb_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('allDay', models.BooleanField(default=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('editable', models.BooleanField(default=False)),
                ('backgroundColor', models.CharField(max_length=255)),
                ('borderColor', models.CharField(max_length=255)),
                ('textColor', models.CharField(max_length=255)),
                ('extendedProps', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
