# Generated by Django 4.1.3 on 2023-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0007_file_report_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeprogram',
            name='backgroundColor',
            field=models.CharField(max_length=10, null='true'),
            preserve_default='true',
        ),
    ]
