# Generated by Django 4.1.3 on 2023-01-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('allDay', models.BooleanField(default=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('editable', models.BooleanField(default=False)),
                ('backgroundColor', models.CharField(max_length=255, null=True)),
                ('borderColor', models.CharField(max_length=255, null=True)),
                ('textColor', models.CharField(max_length=255, null=True)),
                ('extendedProps', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('degree_program', models.ManyToManyField(to='jamapi.degreeprogram')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
