# Generated by Django 4.1.3 on 2023-01-31 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0008_calevent_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calevent',
            name='degree_program',
        ),
        migrations.AddField(
            model_name='calevent',
            name='classNames',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jamapi.degreeprogram'),
        ),
    ]
