# Generated by Django 4.1.3 on 2023-02-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0008_degreeprogram_backgroundcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='degree_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jamapi.degreeprogram'),
            preserve_default=False,
        ),
    ]
