# Generated by Django 4.1.3 on 2023-01-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0009_remove_calevent_degree_program_calevent_classnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='backgroundColor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='borderColor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='extendedProps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='textColor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
