# Generated by Django 4.1.3 on 2023-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0010_alter_calevent_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='start',
            field=models.CharField(max_length=255),
        ),
    ]
