# Generated by Django 4.1.3 on 2023-01-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0011_alter_calevent_end_alter_calevent_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calevent',
            old_name='classNames',
            new_name='className',
        ),
    ]
