# Generated by Django 4.1.3 on 2023-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0008_degreeprogram_backgroundcolor'),
        ('userapi', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='degree_program',
        ),
        migrations.AddField(
            model_name='user',
            name='degree_program',
            field=models.ManyToManyField(to='jamapi.degreeprogram'),
        ),
    ]
