# Generated by Django 4.1.3 on 2023-01-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamapi', '0004_remove_companydetail_acquired_parent_name_and_more'),
        ('userapi', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jamapi.degreeprogram'),
        ),
        migrations.AddField(
            model_name='user',
            name='matriculation_no',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
